version: '2'

services:

  # application
  app:
    build:
      context: ./
      dockerfile: .docker/app.dockerfile
    working_dir: /var/www
    tty: true
    volumes:
      - ./:/var/www
    networks:
      - app-network

  # webserver
  web:
    image: nginx:latest
    working_dir: /var/www
    tty: true
    volumes:
      - ./:/var/www
      - .docker/nginx_conf:/etc/nginx/conf.d
    ports:
      - 80:80
    networks:
      - app-network

  # Database
  database:
    image: mariadb
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
        - 3306:3306
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

# volumes
volumes:
  dbdata:
