version: '2'

services:

  # application
  app:
    build:
      context: ./
      dockerfile: .docker/app.dockerfile
    working_dir: /var/www
    tty: true
    volumes:
      - ./:/var/www
    networks:
      - app-network

  # webserver
  web:
    image: nginx:latest
    working_dir: /var/www
    tty: true
    volumes:
      - ./:/var/www
      - .docker/nginx_conf:/etc/nginx/conf.d
    ports:
      - 80:80
    networks:
      - app-network

  # Database
  database:
    image: postgres
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
        - 5432:5432
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

# volumes
volumes:
  dbdata:
