version: '2'

services:

  # application
  app:
    build:
      context: ./
      dockerfile: .docker/app.dockerfile
    working_dir: /var/www
    tty: true
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    networks:
      - app-network

  # webserver
  web:
    build:
      context: ./
      dockerfile: .docker/web.dockerfile
    working_dir: /var/www
    tty: true
    volumes_from:
      - app
    ports:
      - 80:80
    networks:
      - app-network

  # Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USERNAME}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${DOCKER_DB_ROOT_PASSWORD}"
    ports:
        - "3306:3306"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

# volumes
volumes:
  dbdata:
